# This file was generated by GoReleaser. DO NOT EDIT.
cask "gobackup" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "da02d82b68750eb17cc6b16c5d7b32c778b13abafb185cdf063bf68609376ffb"
      url "https://github.com/senecal-jjs/cmd-line-backup/releases/download/v#{version}/gobackup_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ade417995878ed903b58b996b662f1159eb2644b97d61519b6513361ddd128a2"
      url "https://github.com/senecal-jjs/cmd-line-backup/releases/download/v#{version}/gobackup_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "156b2b19e7ea215eeb0daa81fd54051534eaed426f73c02641c1baaaf274896b"
      url "https://github.com/senecal-jjs/cmd-line-backup/releases/download/v#{version}/gobackup_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "02ec218301cc648d78cb49350a05ed1c28891b2a8d3e1934c9402f85c7dd61d7"
      url "https://github.com/senecal-jjs/cmd-line-backup/releases/download/v#{version}/gobackup_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gobackup"
  desc "Incremental, encrypted, deduplicating backup utility for Amazon S3"
  homepage "https://github.com/senecal-jjs/cmd-line-backup"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gobackup"

  # No zap stanza required

end
