# This file was generated by GoReleaser. DO NOT EDIT.
cask "gobackup" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "17bf8f7af2a59f981ee13f7c0ef5a782e66cb45e6a3b0033ea1ef6ef1518398f"
      url "https://github.com/senecal-jjs/cmd-line-backup/releases/download/v#{version}/gobackup_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "25384454d38d2589ee96c9b1a1f3e9dc88d22b7dd6da32611e3e5b13997c9081"
      url "https://github.com/senecal-jjs/cmd-line-backup/releases/download/v#{version}/gobackup_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "40973a5a4e3b254ce824268e0b44b0c6f3ba6d021add511a0f9477fdd1c4a99a"
      url "https://github.com/senecal-jjs/cmd-line-backup/releases/download/v#{version}/gobackup_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8b25c95d211447087f7012f537e884d373d7efd6ecc3f0d0c0f1639bce50e955"
      url "https://github.com/senecal-jjs/cmd-line-backup/releases/download/v#{version}/gobackup_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gobackup"
  desc "Incremental, encrypted, deduplicating backup utility for Amazon S3"
  homepage "https://github.com/senecal-jjs/cmd-line-backup"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gobackup"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gobackup"]
    end
  end

  # No zap stanza required

end
